server:
  port: 8081
  error:
    include-message: never
    include-exception: false
    include-stacktrace: never
    include-binding-errors: never

spring:
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false

