server:
  port: 8081
#  error:
#    include-message: always
#    include-exception: true
#    include-stacktrace: always
#    include-binding-errors: always

spring:
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false

